<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Photino.NET" Version="4.0.16" />
	<PackageReference Include="CliWrap" Version="3.10.4" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\ParekGIT.Core\ParekGIT.Core.csproj" />
	<ProjectReference Include="..\ParekGIT.Data\ParekGIT.Data.csproj" />
  </ItemGroup>

</Project>
