<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.NET" Version="3.2.3" />
    <PackageReference Include="CliWrap" Version="3.10.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ParekGIT.Core\ParekGIT.Core.csproj" />
    <ProjectReference Include="..\ParekGIT.Data\ParekGIT.Data.csproj" />
  </ItemGroup>

</Project>
